name: ethereum_addresses
description: A dart library to generate, checksum, and validate Ethereum addresses
version: 1.0.3
repository: https://github.com/fuseio/dart-ethereum_address

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  convert: ^3.0.1
  pointycastle: ^4.0.0

dev_dependencies:
  test: ^1.27.0
